# Generated by Django 4.2.1 on 2023-06-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('members', models.IntegerField()),
                ('rent_paid', models.BooleanField(default=False)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('dispute', models.BooleanField(default=False)),
                ('docsverified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.CharField(max_length=20)),
                ('water', models.CharField(max_length=20)),
                ('maintainence', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tenant', to='api.tenant')),
            ],
        ),
    ]
